name: PvPTeams
version: 0.8
author: ViperCobra
main: life.steeze.teamsplugin.TeamsBase
api-version: 1.14
commands:
  accept:
    description: Accept invite
  team:
    description: Teams plugin
  claim:
    description: Make your team's claim
  pos1:
    description: Select position
  pos2:
    description: Select position